[package]
name = "fxconv"
version = "0.1.0"
authors = ["Nicholas Buckeridge <bucknich@gmail.com>"]

[dependencies]
clap = "^2.29.0"
assert_cli = "^0.5"
quickersort = "^3.0.0"
chrono = "^0.4"
time = "^0.1.39"
rand = "0.4.2"
pbr = "1.0.0"
